version: "3"
services:
  python:
    build:
      dockerfile: ./Dockerfile
    image: atcoder
    container_name: atcoder
    tty: true
    volumes:
      - ../../CompProg:/CompProg
      - ./.zshrc:/home/vscode/.zshrc
      - ./.zshrc:/root/.zshrc
