version: "3"
services:
  python:
    build: ./
    image: atcoder
    container_name: atcoder
    tty: true
    volumes:
      - ../../CompProg:/CompProg
      - ./.zshrc:/home/vscode/.zshrc
