a, b, c, d = map(int, input().split())
ans = []
ans.append("U" * (d - b))
ans.append("R" * (c - a))
ans.append("D" * (d - b))
ans.append("L" * (c - a))
ans.append("D")
ans.append("R" * (c - a + 1))
ans.append("U" * (d - b + 1))
ans.append("L")
ans.append("U")
ans.append("L" * (c - a + 1))
ans.append("D" * (d - b + 1))
ans.append("R")
print("".join(ans))
